spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      suffix: .html
      prefix: /templates/


mybatis:
  mapper-locations: classpath:mapper/*.xml

